# TBD

language: go

git:
  depth: false

script:
  - $TRAVIS_BUILD_DIR/travis/bootstrap_etcd.sh "$SYSTEM_TRIPLET" "$PREFERED_ARCHIVE_EXTENSION"
  - $TRAVIS_BUILD_DIR/travis/bootstrap_consul.sh "$SYSTEM_TRIPLET"
  - $TRAVIS_BUILD_DIR/travis/bootstrap_zk.sh

after_failure:
  - $TRAVIS_BUILD_DIR/travis/send_status_message.sh
